services:
  db:
    image: mariadb:11.8
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - db_password
      - db_root_password
    healthcheck:
      test: healthcheck.sh --connect --innodb_initialized || exit 1
      start_period: 3s
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db_data:
